[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'bling/vim-airline'

# カッコ系
[[plugins]]
repo = 'tpope/vim-endwise'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'cohama/lexima.vim'

# テーブル系
[[plugins]]
repo = 'godlygeek/tabular'
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

# Syntax Highlight
  [[plugins]]
  repo = 'scrooloose/syntastic'
  
  [[plugins]]
  repo = 'cespare/vim-toml'
  on_ft = 'toml'

  [[plugins]]
  repo = 'posva/vim-vue'

  [[plugins]]
  repo = 'elzr/vim-json'
  on_ft = ['json']

  [[plugins]]
  repo = 'tmux-plugins/vim-tmux'
  on_ft = ['tmux']

# Markdown用
  [[plugins]]
  repo = 'tyru/open-browser.vim'
  
  [[plugins]]
  repo = 'kannokanno/previm'
  
  [[plugins]]
  repo = 'plasticboy/vim-markdown'
